version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yaml:/traefik.yml"
    networks:
      - blue_green_deploy
    restart: unless-stopped

  blue-web: &web
    container_name: blue-web
    build:
      context: ./src
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.middlewares.test-retry.retry.attempts=5"
      - "traefik.http.middlewares.test-retry.retry.initialInterval=1s"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.services.web.loadbalancer.healthCheck.path=/"
      - "traefik.http.services.web.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.web.loadbalancer.healthCheck.timeout=1s"
    restart: always
    networks:
      - blue_green_deploy

  app-green:
    <<: *web
    container_name: app-green

networks:
  blue_green_deploy:
    driver: bridge
