version: "3.8"

services:
  # influxdb:
  #   image: influxdb:1.8-alpine
  #   container_name: influxdb
  #   environment:
  #     - INFLUXDB_UDP_ENABLED=true
  #     - INFLUXDB_UDP_DATABASE=traefik
  #   ports:
  #     - "127.0.0.1:38089:8089/udp"
  #     - "127.0.0.1:38086:8086"
  #   networks:
  #     - blue_green_deploy
  #   restart: unless-stopped

  traefik:
    image: traefik:v2.9
    container_name: traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yaml:/traefik.yml"
    networks:
      - blue_green_deploy
    restart: unless-stopped

networks:
  blue_green_deploy:
    name: blue_green_deploy
    driver: bridge
